import Head from "next/head";
import Image from "next/image";

import Navigation from '@/components/Navigation';
import ThemesSection from '@/components/ThemesSection';
import VideoSection from '@/components/VideoSection';
import FAQSection from '@/components/FAQSection';
import Footer from '@/components/Footer';

export default function Themes() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-background">
        <Navigation />
        <ThemesSection />
        <VideoSection />
        <FAQSection />
        <Footer />
      </div>
    </>
  );
};